# Generated by Django 5.0.3 on 2024-04-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclib', '0004_alter_musicfiles_cusomuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicfiles',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
