version: "3.9"
services:
  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env
      
    ports:
      - 5432:5432
  
  web:
    container_name: web
    build: 
      context: .
    tty: true
    ports:
     - "8000:8000"
  
    command: >
      sh -c "python -m pip install --upgrade pip && pip install django && pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  
    ports:
      - 8000:8000
    env_file:
      .env
    depends_on:
      - db


 
