# Generated by Django 5.0.3 on 2024-04-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musiclib', '0005_alter_musicfiles_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicfiles',
            old_name='cusomuser',
            new_name='customuser',
        ),
    ]
